apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-node-image.k8s-node.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-node-image.name" . }}
    helm.sh/chart: {{ include "k8s-node-image.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    svc: k8s-node
spec:
  type: {{ .Values.k8sNode.service.type }}
  ports:
    - port: {{ .Values.k8sNode.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "k8s-node-image.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    svc: k8s-node
