apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitlabrunners.miscscripts.pnnl.gov
spec:
  group: miscscripts.pnnl.gov
  names:
    kind: GitlabRunner
    listKind: GitlabRunnerList
    plural: gitlabrunners
    singular: gitlabrunner
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1beta1
    served: true
    storage: true
